package biliutils

import (
	"bilibili-ticket-golang/lib/models/bili/api"
	hashs "bilibili-ticket-golang/lib/utils/hashs"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"time"
)

const publicKeyPEM = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLgd2OAkcGVtoE3ThUREbio0Eg
Uc/prcajMKXvkCKFCWhJYJcLkcM2DKKcSeFpD/j6Boy538YXnR6VhcuUJOhH2x71
nzPjfdTcqMz7djHum0qSZA0AyCBDABUqCrfNgCiJ00Ra7GmRj+YCK1NJEuewlb40
JNrRuoEUXpabUzGB8QIDAQAB
-----END PUBLIC KEY-----`

// CheckAndUpdateCookie verifies login status, checks if a cookie refresh is needed,
// and performs the refresh exchange using RSA-encrypted CSRF tokens.
// Returns (refreshed, error).
func (c *BiliClient) CheckAndUpdateCookie() (bool, error) {
	loginStatus, err := c.GetAccountStatus()
	if err != nil {
		log.Printf("[cookie] GetAccountStatus failed: %v", err)
		return false, err
	}
	if !loginStatus.Login {
		log.Println("[cookie] not logged in, skip refresh")
		return false, nil
	}
	log.Println("[cookie] logged in, checking if refresh needed...")
	refreshNeeded, refreshTimestamp, err := c.checkNeedRefresh()
	if err != nil {
		log.Printf("[cookie] checkNeedRefresh failed: %v", err)
		return false, err
	}
	if !refreshNeeded {
		log.Println("[cookie] refresh not needed")
		return false, nil
	}

	log.Println("[cookie] refresh needed, starting refresh flow...")
	oldCSRF := c.getCSRFFromCookie()
	oldRefreshToken := c.getJarRefreshToken()
	log.Printf("[cookie] old csrf=%s refresh_token=%s", maskToken(oldCSRF), maskToken(oldRefreshToken))

	// Generate RSA-encrypted correspond path for CSRF exchange
	encryptedPath, err := getCorrespondPath(refreshTimestamp)
	if err != nil {
		log.Printf("[cookie] getCorrespondPath failed: %v", err)
		return false, err
	}
	csrfKey, err := c.getRefreshCSRF(encryptedPath)
	if err != nil {
		log.Printf("[cookie] getRefreshCSRF failed: %v", err)
		return false, err
	}
	log.Printf("[cookie] got refresh_csrf=%s", maskToken(csrfKey))

	newRefreshToken, err := c.refreshCookie(oldCSRF, csrfKey, oldRefreshToken)
	if err != nil {
		log.Printf("[cookie] refreshCookie failed: %v", err)
		return false, err
	}
	if newRefreshToken == "" {
		return false, errors.New("refreshCookie returned empty token")
	}
	log.Printf("[cookie] refreshCookie success, new refresh_token=%s", maskToken(newRefreshToken))
	c.SetRefreshToken(newRefreshToken)

	newCSRF := c.getCSRFFromCookie()
	if err = c.setPreviousCookieInvalid(newCSRF, oldRefreshToken); err != nil {
		log.Printf("[cookie] setPreviousCookieInvalid failed: %v", err)
		return false, err
	}
	log.Println("[cookie] old refresh_token invalidated")
	// Persist the new refresh token so it survives restarts
	c.PersistCookies()
	log.Println("[cookie] cookies persisted, refresh complete")
	return true, nil
}

// checkNeedRefresh queries Bilibili's cookie/info endpoint to determine if the
// current cookie session needs to be refreshed.
func (c *BiliClient) checkNeedRefresh() (bool, int64, error) {
	resp, err := c.client.R().Get("https://passport.bilibili.com/x/passport-login/web/cookie/info")
	if err != nil {
		return false, 0, err
	}
	var apiResp api.MainApiDataRoot[api.NeedRefreshStruct]
	if err = resp.Unmarshal(&apiResp); err != nil {
		return false, 0, err
	}
	if err = apiResp.CheckValid(); err != nil {
		return false, 0, err
	}
	if apiResp.Data.NeedRefresh && apiResp.Data.Timestamp <= 0 {
		return false, 0, errors.New("cookie refresh required but server timestamp is missing")
	}
	return apiResp.Data.NeedRefresh, apiResp.Data.Timestamp, nil
}

// getRefreshCSRF parses the CSRF token from Bilibili's correspond page HTML.
// correspondPath is the RSA-encrypted path generated by getCorrespondPath.
func (c *BiliClient) getRefreshCSRF(correspondPath string) (string, error) {
	resp, err := c.client.R().Get(fmt.Sprintf("https://www.bilibili.com/correspond/1/%s", correspondPath))
	if err != nil {
		return "", err
	}
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return "", fmt.Errorf("get refresh csrf: unexpected HTTP status %d", resp.StatusCode)
	}
	htmlBody := resp.String()
	re := regexp.MustCompile(`<div id="1-name">(.*?)</div>`)
	matches := re.FindStringSubmatch(htmlBody)
	if len(matches) > 1 {
		return matches[1], nil
	}
	return "", errors.New("cannot parse RefreshToken from HTML")
}

// refreshCookie calls Bilibili's cookie refresh endpoint to exchange old tokens for new ones.
func (c *BiliClient) refreshCookie(csrfToken, refreshCsrfToken, refreshToken string) (string, error) {
	refreshURL, _ := url.Parse("https://passport.bilibili.com/x/passport-login/web/cookie/refresh")
	resp, err := c.client.R().SetFormData(map[string]string{
		"refresh_token": refreshToken,
		"source":        "main_web",
		"refresh_csrf":  refreshCsrfToken,
		"csrf":          csrfToken,
	}).Post("https://passport.bilibili.com/x/passport-login/web/cookie/refresh")
	if err != nil {
		return "", err
	}
	var apiResp api.MainApiDataRoot[api.RefreshTokenStruct]
	if err = resp.Unmarshal(&apiResp); err != nil {
		return "", err
	}
	if err = apiResp.CheckValid(); err != nil {
		return "", err
	}
	// net/http only replaces cookies with the same name, domain and path. Old
	// versions could leave host-only variants behind, so credential refresh must
	// explicitly make every returned Set-Cookie value authoritative by name.
	if freshCookies := resp.Cookies(); len(freshCookies) > 0 && c.cookieJar != nil {
		if replacer, ok := c.cookieJar.(interface {
			ReplaceCookies(*url.URL, []*http.Cookie)
		}); ok {
			replacer.ReplaceCookies(refreshURL, freshCookies)
		} else {
			c.cookieJar.SetCookies(refreshURL, freshCookies)
		}
	}
	return apiResp.Data.RefreshToken, nil
}

// setPreviousCookieInvalid invalidates the old refresh token after a successful refresh.
func (c *BiliClient) setPreviousCookieInvalid(newCsrf, oldRefreshToken string) error {
	resp, err := c.client.R().SetFormData(map[string]string{
		"refresh_token": oldRefreshToken,
		"csrf":          newCsrf,
	}).Post("https://passport.bilibili.com/x/passport-login/web/confirm/refresh")
	if err != nil {
		return err
	}
	var apiResp api.MainApiDataRoot[interface{}]
	if err = resp.Unmarshal(&apiResp); err != nil {
		return err
	}
	if err = apiResp.CheckValid(); err != nil {
		return err
	}
	return nil
}

// getCSRFFromCookie extracts the bili_jct (CSRF token) from the cookie jar.
func (c *BiliClient) getCSRFFromCookie() string {
	if c.cookieJar == nil {
		return ""
	}
	bilibiliURL, _ := url.Parse("https://www.bilibili.com/")
	for _, cookie := range c.cookieJar.Cookies(bilibiliURL) {
		if cookie.Name == "bili_jct" {
			return cookie.Value
		}
	}
	return ""
}

// getJarRefreshToken returns the refresh token for cookie refresh.
// It is set via SetRefreshToken (called from frontend after QR login succeeds)
// and updated automatically after each successful cookie refresh.
func (c *BiliClient) getJarRefreshToken() string {
	return c.GetRefreshToken()
}

// TryToRefreshNewBiliTicket checks the bili_ticket cookie and refreshes it if
// it will expire within 1 hour. The bili_ticket is required for API access.
// Returns (refreshed, error).
func (c *BiliClient) TryToRefreshNewBiliTicket() (bool, error) {
	if c.cookieJar != nil {
		bilibiliURL, _ := url.Parse("https://www.bilibili.com/")
		// Find the bili_ticket cookie with the latest expiry. If that one
		// still has >= 1 hour left, we don't need to refresh. Otherwise we
		// must refresh even if other cookies look healthy.
		var latest time.Time
		found := false
		for _, cookie := range c.cookieJar.Cookies(bilibiliURL) {
			if cookie.Name != "bili_ticket" {
				continue
			}
			// Session cookies have a zero Expires; treat them as expired
			// so we still refresh and store a real one.
			if cookie.Expires.IsZero() {
				continue
			}
			if !found || cookie.Expires.After(latest) {
				latest = cookie.Expires
				found = true
			}
		}
		if found && time.Until(latest) >= 1*time.Hour {
			return false, nil
		}
	}

	currentTS := c.Now().Unix()
	hexSign := hashs.HmacSha256ToHex("XgwSnGZ1p", fmt.Sprintf("ts%d", currentTS))
	resp, err := c.client.R().SetQueryParams(map[string]string{
		"key_id":      "ec02",
		"hexsign":     hexSign,
		"context[ts]": fmt.Sprintf("%d", currentTS),
		"csrf":        c.getCSRFFromCookie(),
	}).Post("https://api.bilibili.com/bapis/bilibili.api.ticket.v1.Ticket/GenWebTicket")
	if err != nil {
		return false, err
	}
	var apiResp api.MainApiDataRoot[api.BiliTicketStruct]
	if err = resp.Unmarshal(&apiResp); err != nil {
		return false, err
	}
	if err = apiResp.CheckValid(); err != nil {
		return false, err
	}

	if c.cookieJar != nil {
		bilibiliURL, _ := url.Parse("https://www.bilibili.com/")
		c.cookieJar.SetCookies(bilibiliURL, []*http.Cookie{
			{Name: "bili_ticket", Value: apiResp.Data.Ticket, Path: "/", Domain: "bilibili.com", MaxAge: apiResp.Data.TTL},
			{Name: "bili_ticket_expire", Value: fmt.Sprintf("%d", currentTS+int64(apiResp.Data.TTL)), Path: "/", Domain: "bilibili.com", MaxAge: apiResp.Data.TTL},
		})
	}
	return true, nil
}

// getCorrespondPath generates an RSA-OAEP-encrypted correspond path for CSRF exchange.
// The message is "refresh_<timestamp>" encrypted with Bilibili's public key.
func getCorrespondPath(timestamp int64) (string, error) {
	pubKeyBlock, _ := pem.Decode([]byte(publicKeyPEM))
	if pubKeyBlock == nil {
		return "", errors.New("failed to decode public key PEM")
	}
	message := []byte(fmt.Sprintf("refresh_%d", timestamp))
	pubInterface, parseErr := x509.ParsePKIXPublicKey(pubKeyBlock.Bytes)
	if parseErr != nil {
		return "", parseErr
	}
	pubKey := pubInterface.(*rsa.PublicKey)
	encryptedData, encryptErr := rsa.EncryptOAEP(sha256.New(), rand.Reader, pubKey, message, nil)
	if encryptErr != nil {
		return "", encryptErr
	}
	return hex.EncodeToString(encryptedData), nil
}

// maskToken masks a sensitive token for logging: shows at most first 2 and last 2 chars.
func maskToken(s string) string {
	if len(s) < 6 {
		return "***"
	}
	return s[:2] + ".." + s[len(s)-2:]
}
