package reporting

// Stable action names used for cloud-control usage events. Values must never
// contain user input or identifiers; operation-specific data belongs in local
// logs, not in ACTION payloads.
const (
	ActionAppStart          = "APP.START"
	ActionAppStop           = "APP.STOP"
	ActionAppLocaleUpdate   = "APP.LOCALE.UPDATE"
	ActionAppQRTestOpen     = "APP.QR_TEST.OPEN"
	ActionAppPaymentQROpen  = "APP.PAYMENT_QR.OPEN"
	ActionCaptchaTest       = "CAPTCHA.TEST"
	ActionErrorReportTest   = "ERROR_REPORT.TEST"
	ActionTaskLogClear      = "TASK_LOG.CLEAR"
	ActionClusterEventClear = "CLUSTER_EVENT.CLEAR"

	ActionAccountLoginQRStart        = "ACCOUNT.LOGIN.QR.START"
	ActionAccountLoginSMSSend        = "ACCOUNT.LOGIN.SMS.SEND"
	ActionAccountLoginSMSVerify      = "ACCOUNT.LOGIN.SMS.VERIFY"
	ActionAccountLoginPassword       = "ACCOUNT.LOGIN.PASSWORD"
	ActionAccountSafecenterPrepare   = "ACCOUNT.LOGIN.SAFECENTER.PREPARE"
	ActionAccountSafecenterSMSSend   = "ACCOUNT.LOGIN.SAFECENTER.SMS.SEND"
	ActionAccountSafecenterSMSVerify = "ACCOUNT.LOGIN.SAFECENTER.SMS.VERIFY"
	ActionAccountLoginCaptchaPrepare = "ACCOUNT.LOGIN.CAPTCHA.PREPARE"
	ActionAccountTagsUpdate          = "ACCOUNT.TAGS.UPDATE"
	ActionAccountImport              = "ACCOUNT.IMPORT"
	ActionAccountExport              = "ACCOUNT.EXPORT"
	ActionAccountStatusRefresh       = "ACCOUNT.STATUS.REFRESH"
	ActionAccountBuyersSync          = "ACCOUNT.BUYERS.SYNC"
	ActionAccountBuyersSyncAll       = "ACCOUNT.BUYERS.SYNC_ALL"
	ActionAccountBuyersSyncAllFast   = "ACCOUNT.BUYERS.SYNC_ALL_FAST"
	ActionAccountBuyerPhoneUpdate    = "ACCOUNT.BUYER.PHONE.UPDATE"
	ActionAccountBuyerRemove         = "ACCOUNT.BUYER.REMOVE"
	ActionAccountBuyerRemoveAll      = "ACCOUNT.BUYER.REMOVE_ALL"
	ActionAccountDelete              = "ACCOUNT.DELETE"
	ActionBuyerProvision             = "BUYER.PROVISION"
	ActionBuyerSyncStart             = "BUYER.SYNC.START"
	ActionCatalogProjectLoad         = "CATALOG.PROJECT.LOAD"
	ActionCatalogSKUInspect          = "CATALOG.SKU.INSPECT"

	ActionMacroSave             = "MACRO.SAVE"
	ActionMacroDelete           = "MACRO.DELETE"
	ActionMacroRestart          = "MACRO.RESTART"
	ActionPurchaseGroupSave     = "PURCHASE_GROUP.SAVE"
	ActionPurchaseGroupDelete   = "PURCHASE_GROUP.DELETE"
	ActionPurchaseGroupStart    = "PURCHASE_GROUP.START"
	ActionTaskGroupSave         = "TASK_GROUP.SAVE"
	ActionTaskGroupDelete       = "TASK_GROUP.DELETE"
	ActionTaskGroupStart        = "TASK_GROUP.START"
	ActionTaskGroupStop         = "TASK_GROUP.STOP"
	ActionTaskGroupForceStop    = "TASK_GROUP.FORCE_STOP"
	ActionTaskGroupForceRestart = "TASK_GROUP.FORCE_RESTART"
	ActionAttemptStop           = "ATTEMPT.STOP"
	ActionAttemptDeleteTerminal = "ATTEMPT.DELETE_TERMINAL"
	ActionIntentStop            = "INTENT.STOP"
	ActionExecutionSwitchReflow = "EXECUTION.SWITCH_REFLOW"
	ActionOrderPaymentOpen      = "ORDER.PAYMENT.OPEN"

	ActionBWSBindCheck        = "BWS.BIND.CHECK"
	ActionBWSReservationInfo  = "BWS.RESERVATION.INFO"
	ActionBWSTicketBind       = "BWS.TICKET.BIND"
	ActionBWSSubmit           = "BWS.SUBMIT"
	ActionBWSStop             = "BWS.STOP"
	ActionBWSDelete           = "BWS.DELETE"
	ActionBWSLocalEntryAdd    = "BWS.LOCAL.ENTRY.ADD"
	ActionBWSLocalTaskAdd     = "BWS.LOCAL.TASK.ADD"
	ActionBWSLocalEntryRemove = "BWS.LOCAL.ENTRY.REMOVE"

	ActionWorkerTagsUpdate         = "WORKER.TAGS.UPDATE"
	ActionWorkerAdd                = "WORKER.ADD"
	ActionWorkerUpdate             = "WORKER.UPDATE"
	ActionWorkerLocalAdd           = "WORKER.LOCAL.ADD"
	ActionWorkerLocalStart         = "WORKER.LOCAL.START"
	ActionWorkerLocalStop          = "WORKER.LOCAL.STOP"
	ActionWorkerDelete             = "WORKER.DELETE"
	ActionWorkerDisconnect         = "WORKER.DISCONNECT"
	ActionWorkerReconnect          = "WORKER.RECONNECT"
	ActionWorkerForceReconnect     = "WORKER.FORCE_RECONNECT"
	ActionWorkerConfigGenerate     = "WORKER.CONFIG.GENERATE"
	ActionWorkerConfigImport       = "WORKER.CONFIG.IMPORT"
	ActionWorkerConfigForceImport  = "WORKER.CONFIG.FORCE_IMPORT"
	ActionWorkerCaptchaTest        = "WORKER.CAPTCHA.TEST"
	ActionWorkerCaptchaTestAll     = "WORKER.CAPTCHA.TEST_ALL"
	ActionWorkerDeployBinarySelect = "WORKER.DEPLOY.BINARY.SELECT"
	ActionWorkerDeployStart        = "WORKER.DEPLOY.START"
	ActionWorkerDeployCancel       = "WORKER.DEPLOY.CANCEL"

	ActionSettingsRetryIntervalUpdate = "SETTINGS.RETRY_INTERVAL.UPDATE"
	ActionSettingsStartDelayUpdate    = "SETTINGS.START_DELAY.UPDATE"
	ActionSettingsBuyerWorkersUpdate  = "SETTINGS.BUYER_WORKERS.UPDATE"
	ActionNotifyChannelAdd            = "NOTIFY.CHANNEL.ADD"
	ActionNotifyChannelRemove         = "NOTIFY.CHANNEL.REMOVE"
	ActionNotifyChannelUpdate         = "NOTIFY.CHANNEL.UPDATE"
	ActionNotifyChannelTest           = "NOTIFY.CHANNEL.TEST"
)
